### ISSUE TITLE
newImageData is null in iOS

### ISSUE THREAD

**Issue by ghost** [brunobar79/J-I-C#12]
compress: function(source_img_obj, quality, output_format){  
             var mime_type = "image/jpeg";
             if(typeof output_format !== "undefined" && output_format=="png"){
                mime_type = "image/png";
             }
             var cvs = document.createElement("canvas");
             cvs.width = source_img_obj.naturalWidth;
             cvs.height = source_img_obj.naturalHeight;
             cvs.getContext("2d").drawImage(source_img_obj, 0, 0);
             var newImageData = cvs.toDataURL(mime_type, quality/100);
             var result_image_obj = new Image();
             result_image_obj.src = newImageData;
             return result_image_obj;
        },

I am getting newImageData  ==> "data:,"

does this plugin work for iOS? 

Scenario : I want to take picture from iPad camera and upload on our server after compressing it.

**Comment by IsaiahJTurner** [comment]
@brunobar79 This issue remains, not sure why it was closed.
@Karan-Sapkale Did you find a workaround?

**Comment by Karan-Sapkale** [comment]
Hi!

I used https://github.com/gokercebeci/canvasResize plugin along with
brunobar plugin. Because my all code was compatible with brunobar plugin.
Using hybrid solution. I did IT!!!

Let me know if you want source code... I'll provide you

Regards,
Karan

On Mon, Jan 12, 2015 at 2:36 PM, Isaiah J Turner <notifications@github.com>
wrote:

> @brunobar79 <https://github.com/brunobar79> This issue remains, not sure
> why it was closed.
> @Karan-Sapkale <https://github.com/Karan-Sapkale> Did you find a
> workaround?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brunobar79/J-I-C/issues/12#issuecomment-69543045>.
>



-- 
Cheers!
Karan Sapkale

**Comment by JonasNielsen** [comment]
@Karan-Sapkale, I'd love to see what you put together. Struggling with the same issue with iOS support.

**Comment by Karan-Sapkale** [comment]
Sure,
I'll share code with you.

**Comment by JonasNielsen** [comment]
@Karan-Sapkale are you sharing it here?

**Comment by Karan-Sapkale** [comment]
Yup,
I'll email you the source code in zip file. Because that module i made is
for private people

**Comment by Karan-Sapkale** [comment]
Hi,

Please see attached.

Dig.Tweek.Break.

Enjoy :)

On Thu, Apr 9, 2015 at 1:42 PM, Karan Sapkale <karan.sapkale@gmail.com>
wrote:

> Yup,
> I'll email you the source code in zip file. Because that module i made is
> for private people
> On 09-Apr-2015 1:40 pm, "Jonas Bruun Nielsen" <notifications@github.com>
> wrote:
>
>> @Karan-Sapkale <https://github.com/Karan-Sapkale> are you sharing it
>> here?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/brunobar79/J-I-C/issues/12#issuecomment-91145789>.
>>
>


-- 
Cheers!
Karan Sapkale

**Comment by JonasNielsen** [comment]
@Karan-Sapkale, sorry but the attachment does not go through when replying to Github. You are welcome to email me at jonas@jonasbnielsen.dk

**Comment by Karan-Sapkale** [comment]
I thought as well,

Please check your email.

On Fri, Apr 10, 2015 at 11:59 AM, Jonas Bruun Nielsen <
notifications@github.com> wrote:

> @Karan-Sapkale <https://github.com/Karan-Sapkale>, sorry but the
> attachment does not go through when replying to Github. You are welcome to
> email me at jonas@jonasbnielsen.dk
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brunobar79/J-I-C/issues/12#issuecomment-91449808>.
>



-- 
Cheers!
Karan Sapkale

**Comment by shaopaul** [comment]
@JonasNielsen  hi, I met the same problem here. Could send me the solution code to me?  My email: shaopaul05@163.com

**Comment by JonasNielsen** [comment]
@shaopaul, @ghost's solution did not solve all my problems, unfortunately. As far as I remember, I ended up switching to another approach. I'll leave it to @ghost to share the code since it's confidential.
