### ISSUE TITLE
You Will Not support for iPhone iOS Safari

### ISSUE THREAD

**Issue by DemonCloud** [brunobar79/J-I-C#18]
have any method?

if your upload file large than 2M size. canvas will be broken on Safari

I've experienced the same problem. It seems that this is an iOS limitation, jpg over 2 megapixel are subsampled.

See Creating Compatible Web Content for Safari on IPhone
https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/CreatingContentforSafarioniPhone/CreatingContentforSafarioniPhone.html

https://stackoverflow.com/questions/11929099/html5-canvas-drawimage-ratio-bug-ios

**Comment by brunobar79** [comment]
Check out this demo and let me know:  http://makeitsolutions.com/labs/demo2/

It has a modified version that works fine on ios / safari/

**Comment by clcpolevaulter** [comment]
@brunobar79 has that modified version been integrated into the distribution yet?

**Comment by brunobar79** [comment]
No because it's a hack with minimal support (might break with big images,
doesn't support different orientations, etc) but feel free to contribute!
