### ISSUE TITLE
Multiple File Uploads

### ISSUE THREAD

**Issue by viditgoyal3009** [brunobar79/J-I-C#21]
Please inform me how do i compress multiple images.

I have made an online gallery where people can upload multiple images at once and i want that the entire images be compressed before being uploaded.

**Comment by brunobar79** [comment]
This is not an issue, It's a feature request and I don't think it's gonna be added to the library in a near future.

About your options,  
1) Tweak the library to handle a queue of images.
2) Call compress and upload for each of your images.

If you end up doing 1) and you think it's cool, feel free to submit a PR.
Thanks!
