### ISSUE TITLE
png compression

### ISSUE THREAD

**Issue by mallt** [brunobar79/J-I-C#22]
I've been testing png compression on http://makeitsolutions.com/labs/jic/, but after compression the file seems to be bigeer than the original file.

This png image for example has a size of 2462 kb, and goes to 2794 kb after compression with a selected compression ratio of 30% in google chrome:
http://pngimg.com/upload/water_PNG3277.png

Thanks!

**Comment by CosmicWebServices** [comment]
Same thing here.

**Comment by brunobar79** [comment]
Hey guys, I did a little research and this is not a library issue. It's a known bug in Chrome.
Please see https://code.google.com/p/chromium/issues/detail?id=179289

I recommend you to vote this issue to give it more relevance.

**Comment by CosmicWebServices** [comment]
ok
