### ISSUE TITLE
Possible large file compression issues

### ISSUE THREAD

**Issue by sonnyk22** [brunobar79/J-I-C#23]
Great library.  

I tried the JIC's demo link to upload a large .jpg (size: 4.6mb) file at the link below (after downloading the image onto my computer first)

http://www.kenrockwell.com/nikon/d810/sample-images/810_4051.JPG

At the Compression ratio of 5% or any up to 30% that I've tried, I've gotten output images that ranged between 2 to 4 times the original filesize.

For example:
   Compression ratio: 5%
   Original filesize: 4764.8720703125 Kb
   JIC Compress/uploaded filesize: 14001.7578125 Kb

Am I doing this correctly on your demo site?

**Comment by brunobar79** [comment]
I think this is related to #24 which I just merged in.
