### ISSUE TITLE
Target Image Size Parameter

### ISSUE THREAD

**Issue by toddmo** [brunobar79/J-I-C#25]
Hello, how hard is it to add a target image size (file size) parameter?

Instead of guessing at what quality will achieve what size.

My own head can think of a binary search algorithm whereby it tries 5-6 iterations attempting to get just under the target max file size. I can use your library to achieve this. But if you have a easier way based on your inside knowledge can we make this a feature?

**Comment by brunobar79** [comment]
I'd go with binary search.  You can include some parameters like number of attempts or threshold, like how close you wanna get to that number.
