### ISSUE TITLE
Security issue.

### ISSUE THREAD

**Issue by vishcodez** [brunobar79/J-I-C#28]
Great source available. However there is an error on the below line any support can be expected please.

` var newImageData = canvas.toDataURL(mime_type, quality/100);`

Error on console:

`Uncaught SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.`

Here is my code:

[sample.txt](https://github.com/brunobar79/J-I-C/files/184762/sample.txt)

**Comment by brunobar79** [comment]
Check this out: http://stackoverflow.com/a/20424457/1236940
