### ISSUE TITLE
PNG's getting larger after compression

### ISSUE THREAD

**Issue by justin-glorvigen** [brunobar79/J-I-C#29]
I can't seem to get it to actually compress a png file on the demo page. I tried the attached file with the default compression ratio of 30 and the file size went from 2765KB for the source file to 4089KB for the "compressed" file. I also tried different compression ratios but they didn't seem to change anything in the output file.

![03-23-2016-07-33-20--153290107-02-09-2016-11-53-15--1869943628-image6](https://cloud.githubusercontent.com/assets/7796859/15366153/3b99bebe-1ce0-11e6-9d8b-f39fd802b717.png)

**Comment by genesiscz** [comment]
Take a look [here](https://github.com/brunobar79/J-I-C/pull/24). It may help a lot

**Comment by brunobar79** [comment]
I just merged in @genesiscz PR #24  so this should be fixed.
