### ISSUE TITLE
the duringCallback doesn't work for me

### ISSUE THREAD

**Issue by dh-Chen** [brunobar79/J-I-C#32]
hi, thanks for the code!! it works fine for me. But i came out with a problem while using it.
in my code, i try to use as follow:
`jic.upload(img, "/uploadImge", "image", "t."+output_format, uploadImg1, errorCallback, duringCallback, customHeaders);`
and
`    var duringCallback = function (progressPercent) {
       $("#percent").html(progressPercent);
    };`
but it seems that it never invoke the duringCallback to show the progressPercent. can you tell me how to use it. 
Thanks!

**Comment by brunobar79** [comment]
Hey, it looks like there was a bug with that, but I just merged in a fix for it (See #31)  So I recommend you to pull the latest code and give a try

**Comment by brunobar79** [comment]
Feel free to re-open if this doesn't work.

**Comment by dh-Chen** [comment]
It works! Thanks
