### ISSUE TITLE
Decleration target_img

### ISSUE THREAD

**Issue by Isengo1989** [brunobar79/J-I-C#44]
:54 Uncaught SyntaxError: Unexpected token .

`target_img.src = jic.compress(file,quality,output_format).src;
`

**Comment by brunobar79** [comment]
@Isengo1989 browser?

**Comment by Isengo1989** [comment]
Chrome. But I got it working. My bad.

I got to compress it, but now I want to upload it, but leave that to my Controller in PHP. Can I simply just change the .src ?

**Comment by brunobar79** [comment]
I don't understand what are you trying to do. Can you provide an example?

PHP's job is to process your upload.    Compression & upload to the server
happens on the JS side.

**Comment by Isengo1989** [comment]
I am trying to upload the File with the compressed data. I saw you are using upload.php - is it possible without that .php file?

Want to use this in Framework and keep this as clean as possible.

**Comment by brunobar79** [comment]
That's a server side script to process your upload. I've choosen PHP cause
it's simple but you can use whatever you want. You will need some server
side lang. to process your upload.

**Comment by shahz5678** [comment]
@Isengo1989 i am getting the same error;
:54 Uncaught SyntaxError: Unexpected token .
target_img.src = jic.compress(file,quality,output_format).src;
Also I am using Chrome. How did you resolve this issue?
