### ISSUE TITLE
Not Working when i upload file 

### ISSUE THREAD

**Issue by A7medMarzouk1** [brunobar79/J-I-C#45]
I'm trying to use this library but without dropping an image 
I upload image file and return base64 of it
and remove the uploaded file 
Then i set this base64 to  img 
i also make another img  as result image
when I call the function of compress 
give me that error

Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'

can I use it without using img 
i give it base64 and it return base64 to me

**Comment by A7medMarzouk1** [comment]
I solved it 👍

**Comment by martinop** [comment]
how you solve it?

**Comment by A7medMarzouk1** [comment]
I user ajax to upload file to the server and and return the base64 for the image to call JIC

//PHP
$deleted_path = 'uploads/'.$file_name;
$type = pathinfo($path, PATHINFO_EXTENSION);
$data = file_get_contents($path);
$base64 = 'data:image/' . $type . ';base64,' . base64_encode($data);
unlink($deleted_path);


then by using JS I created image tag and create the new image and save the output of JIC in it

//JS
var img = document.createElement("img");
var quality = 30;
var output_format = "jpg";
var result_image = jic.compress(img,quality,output_format).src;
save_image_on_server(result_image,hidden_field)
// hidden_field , this field is html element to return the output of saving on it

**Comment by Aravind-Bhat** [comment]
How do i compress the PNG Image?
