### ISSUE TITLE
Link broken in README.md

### ISSUE THREAD

**Issue by Walt-H** [brunobar79/J-I-C#57]
Hello :)

Trying to see the working example at link in the README, I came across the following error page:
![screen shot 2018-07-18 at 2 44 12 pm](https://user-images.githubusercontent.com/3917475/42901241-0f310656-8a99-11e8-8054-41c0bb371d53.png)

Just wanted to see if this was an error, or maybe the examples moved elsewhere.

**Comment by brunobar79** [comment]
Thanks for reporting. Just fixed it!

**Comment by satyam8080** [comment]
Your demo website is not working
